### ISSUE TITLE
npm run start.ios encounter error

### ISSUE THREAD

**Issue by seawenzhu** [shripalsoni04/ngxp-quotes-app#2]
ngxp-quotes-app-master npm run start.ios

> ngxp-quotes-app@1.0.0 start.ios /Users/seawenzhu/Downloads/ngxp-quotes-app-master
> cd nativescript && tns run ios

Executing before-prepare hook from /Users/seawenzhu/Downloads/ngxp-quotes-app-master/nativescript/hooks/before-prepare/nativescript-dev-sass.js
/Users/seawenzhu/Downloads/ngxp-quotes-app-master/nativescript/app/app.android.scss SASS CSS pre-processing failed. Error: Error: File to import not found or unreadable: nativescript-theme-core/scss/themes/core/variables_dark.
Parent style sheet: /Users/seawenzhu/Downloads/ngxp-quotes-app-master/nativescript/app/scss/_variables.scss
Sending exception report (press Ctrl+C to stop).....

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/seawenzhu/.nvm/versions/node/v6.2.0/bin/node" "/Users/seawenzhu/.nvm/versions/node/v6.2.0/bin/npm" "run" "start.ios"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ngxp-quotes-app@1.0.0 start.ios: `cd nativescript && tns run ios`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ngxp-quotes-app@1.0.0 start.ios script 'cd nativescript && tns run ios'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ngxp-quotes-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd nativescript && tns run ios
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ngxp-quotes-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ngxp-quotes-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/seawenzhu/Downloads/ngxp-quotes-app-master/npm-debug.log
➜  ngxp-quotes-app-master

**Comment by seawenzhu** [comment]
Hi, 
     after I change the theme core path to correct it can build success, but app is crash on ios with following error: 

Project successfully built
Successfully deployed on device with identifier '3F0DC413-B249-44FF-8CC3-6A57759C1D2F'.
1   0x10fdba5dc -[TNSRuntime executeModule:referredBy:]
2   0x10e7f3072 main
3   0x1130f492d start
Dec 16 17:12:25 seawenzhudeMacBook-Pro nativescript[24172]: f**ile:///app/tns_modules/@angular/core/bundles/core.umd.js:7:92: JS ERROR Error: Could not find module 'rxjs/Subject'. Computed path '/Users/seawenzhu/Library/Developer/CoreSimulator/Devices/3F0DC413-B249-44FF-8CC3-6A57759C1D2F/data/Containers/Bundle/Application/80A32125-354A-4226-B3AC-A64554CC494A/nativescript.app/app/tns_modules/rxjs/Subject'.**
Dec 16 17:12:25 seawenzhudeMacBook-Pro com.apple.CoreSimulator.SimDevice.3F0DC413-B249-44FF-8CC3-6A57759C1D2F.launchd_sim[23312] (UIKitApplication:io.ngxp.quotesapp[0xf377][24172]): Service exited due to signal: Segmentation fault: 11

**Comment by shripalsoni04** [comment]
Hi,

Thanks for reporting bug.

I have upgraded dependencies of angular, tns-core-theme and other related dependencies and pushed changes to master branch. I have also tested it on Android, iOS and Web and it is working properly now.

Closing this issue for now. Feel free to reopen if you still face any issue.
